### ISSUE TITLE
eventHub Name is hardcoded in the function.json

### ISSUE THREAD

**Issue by djsly** [SumoLogic/sumologic-azure-function#27]
https://github.com/SumoLogic/sumologic-azure-function/blob/6dc2a0c68f689990e7011750bedb4272b0f36bf3/EventHubs/target/logs_build/EventHubs_Logs/function.json#L7

while the EventHUb name is configurable. 

https://github.com/SumoLogic/sumologic-azure-function/blob/03b6296228eeb16dc5ea05d38486e27f699259a9/EventHubs/src/azuredeploy_logs.json#L25-L27

The same variable should be used for the Function Code

**Comment by himanshu219** [comment]
yes actually by default azure monitor creates this hub(specially activity logs). Any particular instance where you're getting a different name.
