### ISSUE TITLE
Upgrade function app to v3.x

### ISSUE THREAD

**Issue by CameronMcAuley** [SumoLogic/sumologic-azure-function#43]
Hello,

We use this function and our auditor has raised a security concern that Diagnostic Logs are not enabled for the App Function.
Unfortunately it seems that we can only enable diagnostic logs for v2.x or v3.x App functions.
I have looked in the repo and it seems this is still on v1.x.

Are there any plans to upgrade this?
Thanks

**Comment by CameronMcAuley** [comment]
Any updates on this? 
Is this repo maintained?

**Comment by himanshu219** [comment]
Block and Metrics function are migrated to 4.x now
